apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: db-backup-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
  - apiGroups:
      - "sql.cnrm.cloud.google.com"
    resources:
      - sqldatabases
      - sqlinstances
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: db-backup-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: db-backup-role
subjects:
  - kind: ServiceAccount
    name: db-backup
    namespace: nais
