name: Build and deploy db-backup
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test_and_lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - uses: jdx/mise-action@v4

      - name: Run tests
        run: mise run test

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # ratchet:golangci/golangci-lint-action@v6
        with:
          version: v2

  build_and_push:
    name: Build and sign image to GAR
    needs: test_and_lint
    outputs:
      image: ${{ steps.build-push-sign.outputs.image }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # ratchet:nais/docker-build-push@v0
        id: build-push-sign
        with:
          team: nais
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy_to_prod:
    name: Deploy to nais prod-gcp
    needs: build_and_push
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/naisjob.yaml,nais/alert.yaml
          VAR: image=${{ needs.build_and_push.outputs.image }}
          VARS: nais/prod.json
